[package]
name = "lhy_blog_os"
version = "0.1.0"
authors = ["Li Hongyu <lihongyu1999@bupt.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
